[package]
name = "rust-submitmessage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.5.0"
ed25519-dalek = {version = "2.0.0", features = ["rand_core"]}
rand = "0.8.5"
hex = "0.4.3"
protobuf = "3.7.2"
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }

[build-dependencies]
protobuf-codegen-pure = "2.25.2"

